
# -- String to partially override the pod and service names. Will maintain the
# release name.
nameOverride: ""
# -- String to fully override the pod and service names. If set, deployments,
# services, ingresses, *etc*, will use this name, and `nameOverride` will be
# ignored.
fullnameOverride: ""

global:
  # -- Used by Wharf to differentiate between installations in the same
  # namespace.
  instanceId: dev

common:
  # -- Default logging level for all components.
  # Possible values: `debug`, `info`, `warn`, `error`, and `panic`.
  loglevel: debug

  # -- Default Docker image for all components.
  # The same image can be used for all wharf-cmd components as it uses the same
  # binary to perform the different tasks.
  image: quay.io/iver-wharf/wharf-cmd:v0.8.0

  # -- Default imagePullPolicy for all components.
  # [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  imagePullPolicy: ""

  # -- Default imagePullSecrets for all components.
  # [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
  imagePullSecrets: []
  #  - name: myDockerCredentialsSecret

  # -- Default configuration for all components.
  # This is later merged with each per-component configs, where their config
  # values take precedence. [Read more (pkg.go.dev/github.com/iver-wharf/wharf-cmd)](https://pkg.go.dev/github.com/iver-wharf/wharf-cmd/pkg/config)
  config: {}

aggregator:
  # -- Enable the wharf-cmd-aggregator component.
  enabled: true

  # -- Docker image of wharf-cmd-aggregator.
  # @default -- common.image
  image: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  # @default -- common.imagePullPolicy
  imagePullPolicy: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
  # @default -- common.imagePullSecrets
  imagePullSecrets: []
  #  - name: myDockerCredentialsSecret

  # -- (string) Logging level for wharf-cmd-aggregator.
  # Possible values: `debug`, `info`, `warn`, `error`, and `panic`.
  # @default -- common.loglevel
  loglevel: null

  # -- Selects which node to run on, based on node labels.
  # [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/)
  nodeSelector:
    kubernetes.io/os: linux

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  tolerations: []
  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity: {}

  # -- Environment variables to add to the container.
  # [Read more (kubernetes.io)](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  extraEnvs: []

  # -- Arguments to add to the container. E.g `[ "--another-arg", "value" ]`
  extraArgs: []

  # -- Configuration for wharf-cmd added only to the aggregator component.
  # This is merged with `common.config`, where values here take precedence.
  # [Read more (pkg.go.dev/github.com/iver-wharf/wharf-cmd)](https://pkg.go.dev/github.com/iver-wharf/wharf-cmd/pkg/config)
  # @default -- common.config
  config: {}

provisioner:
  # -- Enable the wharf-cmd-provisioner component.
  enabled: true

  # -- Docker image of wharf-cmd-provisioner.
  # @default -- common.image
  image: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  # @default -- common.imagePullPolicy
  imagePullPolicy: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
  # @default -- common.imagePullSecrets
  imagePullSecrets: []
  #  - name: myDockerCredentialsSecret

  # -- (string) Logging level for wharf-cmd-provisioner.
  # Possible values: `debug`, `info`, `warn`, `error`, and `panic`.
  # @default -- common.loglevel
  loglevel: null

  # -- Service type. [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types)
  serviceType: ClusterIP

  # -- Service port. [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service)
  servicePort: 80

  # -- Container port. This needs to correlate to the port that the application
  # listens on. [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service)
  containerPort: 5009

  # -- Selects which node to run on, based on node labels.
  # [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/)
  nodeSelector:
    kubernetes.io/os: linux

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  tolerations: []
  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity: {}

  # -- Environment variables to add to the container.
  # [Read more (kubernetes.io)](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  extraEnvs: []

  # -- Arguments to add to the container. E.g `[ "--another-arg", "value" ]`
  extraArgs: []

  # -- Configuration for wharf-cmd added only to the provisioner component.
  # This is merged with `common.config`, where values here take precedence.
  # [Read more (pkg.go.dev/github.com/iver-wharf/wharf-cmd)](https://pkg.go.dev/github.com/iver-wharf/wharf-cmd/pkg/config)
  # @default -- common.config
  config: {}

watchdog:
  # -- Enable the wharf-cmd-watchdog component.
  enabled: false

  # -- Docker image of wharf-cmd-watchdog.
  # @default -- common.image
  image: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  # @default -- common.imagePullPolicy
  imagePullPolicy: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
  # @default -- common.imagePullSecrets
  imagePullSecrets: []
  #  - name: myDockerCredentialsSecret

  # -- (string) Logging level for wharf-cmd-watchdog.
  # Possible values: `debug`, `info`, `warn`, `error`, and `panic`.
  # @default -- common.loglevel
  loglevel: null

  # -- Selects which node to run on, based on node labels.
  # [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/assign-pods-nodes/)
  nodeSelector:
    kubernetes.io/os: linux

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/)
  tolerations: []
  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
  affinity: {}

  # -- Environment variables to add to the container.
  # [Read more (kubernetes.io)](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  extraEnvs: []

  # -- Arguments to add to the container. E.g `[ "--another-arg", "value" ]`
  extraArgs: []

  # -- Configuration for wharf-cmd added only to the watchdog component.
  # This is merged with `common.config`, where values here take precedence.
  # [Read more (pkg.go.dev/github.com/iver-wharf/wharf-cmd)](https://pkg.go.dev/github.com/iver-wharf/wharf-cmd/pkg/config)
  # @default -- common.config
  config: {}

worker:
  # -- Docker image of wharf-cmd-worker.
  # @default -- common.image
  image: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/concepts/containers/images/#updating-images)
  # @default -- common.imagePullPolicy
  imagePullPolicy: ""

  # -- [Read more (kubernetes.io/docs)](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)
  # @default -- common.imagePullSecrets
  imagePullSecrets: []
  #  - name: myDockerCredentialsSecret

  # -- Environment variables to add to the container.
  # [Read more (kubernetes.io)](https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container/)
  extraEnvs: []

  # -- Arguments to add to the container. E.g `[ "--another-arg", "value" ]`
  extraArgs: []

  # -- Configuration for wharf-cmd added only to the worker component.
  # This is merged with `common.config`, where values here take precedence.
  # [Read more (pkg.go.dev/github.com/iver-wharf/wharf-cmd)](https://pkg.go.dev/github.com/iver-wharf/wharf-cmd/pkg/config)
  # @default -- common.config
  config: {}

  # -- Wharf built-in variables to use in a build. Each key-value pair will be
  # available to all builds.
  vars: {}
  #  CHART_REPO: https://harbor.local/chartrepo
  #  REG_URL: harbor.local
  #  REG_SECRET: harbor-registry
