apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wharf-helm.fullname" . }}-api
  labels:
    {{- include "wharf-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      component: api
      {{- include "wharf-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: api
        {{- include "wharf-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wharf-helm.serviceAccountName" . }}
      {{- with .Values.api.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name | quote }}
          {{- with .Values.api.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.api.image | quote }}
          {{- with .Values.api.imagePullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.global.instanceId }}
            - name: WHARF_INSTANCEID
              value: {{ quote . }}
            {{- end }}
            - name: WHARF_CI_TRIGGERURL
              {{- .Values.api.ciUrl | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_CI_TRIGGERTOKEN
              {{- .Values.api.ciToken | include "wharf-helm.environmentValue" | nindent 14 }}

            {{- with .Values.api.http }}
            - name: WHARF_HTTP_BASICAUTH
              {{- .basicAuth | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_HTTP_BINDADDRESS
              {{- .bindAddress | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_HTTP_OIDC_ENABLE
              {{- .enable }}
            - name: WHARF_HTTP_OIDC_ISSUERURL
              {{- .issuerURL }}
            - name: WHARF_HTTP_OIDC_AUDIENCEURL
              {{- .audienceURL }}
            - name: WHARF_HTTP_OIDC_KEYSURL
                {{- .keysURL }}
            {{- end }}{{/* with .Values.api.http */}}

            {{- if .Values.global.isProduction }}
            - name: GIN_MODE
              value: release
            {{- end }}

            {{- with .Values.api.db }}
            {{- if $.Values.global.isProduction }}
            - name: WHARF_DB_LOG
              {{- "false" | include "wharf-helm.environmentValue" | nindent 14 }}
            {{- else }}
            - name: WHARF_DB_LOG
              {{- "true" | include "wharf-helm.environmentValue" | nindent 14 }}
            {{- end }}{{/* if $.Values.global.isProduction */}}
            - name: WHARF_DB_DRIVER
              {{- .driver | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_NAME
              {{- .name | include "wharf-helm.environmentValue" | nindent 14 }}
            {{- if eq .driver "postgres" }}
            - name: WHARF_DB_USERNAME
              {{- .username | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_PASSWORD
              {{- .password | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_PORT
              {{- .port | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_HOST
              {{- .host | include "wharf-helm.environmentValue" | nindent 14 }}
            {{- end }}{{/* if .driver == "postgres" */}}
            - name: WHARF_DB_MAXIDLECONNS
              {{- .maxIdleConns | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_MAXOPENCONNS
              {{- .maxOpenConns | include "wharf-helm.environmentValue" | nindent 14 }}
            - name: WHARF_DB_MAXCONNLIFETIME
              {{- .maxConnLifetime | include "wharf-helm.environmentValue" | nindent 14 }}
            {{- end }}{{/* with .Values.api.db */}}

            {{- with .Values.api.extraEnvs }}
              {{- toYaml . | nindent 12}}
            {{- end }}
          {{- with .Values.api.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wharf-helm.fullname" . }}-api
  labels:
    {{- include "wharf-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType | quote }}
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: api
    {{- include "wharf-helm.selectorLabels" . | nindent 4 }}
---
