---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wharf-helm.fullname" . }}-api
  labels:
    {{- include "wharf-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      component: api
      {{- include "wharf-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: api
        {{- include "wharf-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wharf-helm.serviceAccountName" . }}
      {{- with .Values.api.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name | quote }}
          {{- with .Values.api.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.api.image | quote }}
          {{- with .Values.api.imagePullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          {{- with .Values.api.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.api.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            {{- with .Values.global.instanceId }}
            - name: WHARF_INSTANCE
              value: {{ quote . }}
            - name: WHARF_INSTANCEID
              value: {{ quote . }}
            {{- end }}
            {{- list .Values.api.ciUrl "CI_URL" "WHARF_CI_TRIGGERURL" | include "wharf-helm.environment" | nindent 12 }}
            {{- list .Values.api.ciToken "CI_TOKEN" "WHARF_CI_TRIGGERTOKEN" | include "wharf-helm.environment" | nindent 12 }}

            {{- with .Values.api.http }}
              {{- list .basicAuth "BASIC_AUTH" "WHARF_HTTP_BASICAUTH" | include "wharf-helm.environment" | nindent 12 }}
              {{- list .bindAddress "BIND_ADDRESS" "WHARF_HTTP_BINDADDRESS" | include "wharf-helm.environment" | nindent 12 }}
            {{- end }}{{/* with .Values.api.http */}}

            {{- if .Values.global.isProduction }}
            - name: GIN_MODE
              value: release
            {{- end }}

            {{- with .Values.api.rabbitmq }}
              {{- if .enabled }}
                {{- list "true" "RABBITMQENABLED" "WHARF_MQ_ENABLED" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .username "RABBITMQUSER" "WHARF_MQ_USERNAME" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .password "RABBITMQPASS" "WHARF_MQ_PASSWORD" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .host "RABBITMQHOST" "WHARF_MQ_HOST" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .port "RABBITMQPORT" "WHARF_MQ_PORT" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .vHost "RABBITMQVHOST" "WHARF_MQ_VHOST" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .name "RABBITMQNAME" "WHARF_MQ_QUEUENAME" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .connAttempts "RABBITMQCONNATTEMPTS" "WHARF_MQ_CONNATTEMPTS" | include "wharf-helm.environment" | nindent 12 }}
              {{- else }}
                {{- list "false" "RABBITMQENABLED" "WHARF_MQ_ENABLED" | include "wharf-helm.environment" | nindent 12 }}
              {{- end }}{{/* if .enabled */}}
            {{- end }}{{/* with .Values.api.rabbitmq */}}

            {{- with .Values.api.db }}
              {{- if $.Values.global.isProduction }}
                {{- list "false" "DBLOG" "WHARF_DB_LOG" | include "wharf-helm.environment" | nindent 12 }}
              {{- else }}
                {{- list "true" "DBLOG" "WHARF_DB_LOG" | include "wharf-helm.environment" | nindent 12 }}
              {{- end }}{{/* if $.Values.global.isProduction */}}
              {{- list .driver "DBDRIVER" "WHARF_DB_DRIVER" | include "wharf-helm.environment" | nindent 12 }}
              {{- list .name "DBNAME" "WHARF_DB_NAME" | include "wharf-helm.environment" | nindent 12 }}
              {{- if eq .driver "postgres" }}
                {{- list .username "DBUSER" "WHARF_DB_USERNAME" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .password "DBPASS" "WHARF_DB_PASSWORD" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .port "DBPORT" "WHARF_DB_PORT" | include "wharf-helm.environment" | nindent 12 }}
                {{- list .host "DBHOST" "WHARF_DB_HOST" | include "wharf-helm.environment" | nindent 12 }}
              {{- end }}{{/* if .driver == "postgres" */}}
              {{- list .maxIdleConns "DBMAXIDLECONNS" "WHARF_DB_MAXIDLECONNS" | include "wharf-helm.environment" | nindent 12 }}
              {{- list .maxOpenConns "DBMAXOPENCONNS" "WHARF_DB_MAXOPENCONNS" | include "wharf-helm.environment" | nindent 12 }}
              {{- list .maxConnLifetime "DBMAXCONNLIFETIME" "WHARF_DB_MAXCONNLIFETIME" | include "wharf-helm.environment" | nindent 12 }}
            {{- end }}{{/* with .Values.api.db */}}

            {{- with .Values.api.extraEnvs }}
              {{- toYaml . | nindent 12}}
            {{- end }}
          {{- with .Values.api.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wharf-helm.fullname" . }}-api
  labels:
    {{- include "wharf-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType | quote }}
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: api
    {{- include "wharf-helm.selectorLabels" . | nindent 4 }}
---
