{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "wharf-helm.fullname" . -}}
{{- $svcPortWeb := .Values.web.servicePort -}}
{{- $svcPortApi := .Values.api.servicePort -}}
{{- $ingressRouteApiVersion := .Values.ingressRoute.apiVersion | default "traefik.containo.us/v1alpha1" -}}
{{- $url := .Values.global.url }}
{{- $labels := include "wharf-helm.labels" . }}

{{- range $index, $entry := .Values.ingressRoute.entries -}}
apiVersion: {{ $ingressRouteApiVersion | quote }}
kind: IngressRoute
metadata:
  name: {{ printf "%v-%v" $fullName $entry.name | quote }}
  labels: {{- $labels | nindent 4 }}
  {{- with $entry.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints: {{- toYaml $entry.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ $url }}`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ printf "%v-web" $fullName | quote }}
          port: {{ $svcPortWeb }}
      {{- with .middlewares }}
      middlewares: {{- toYaml . | nindent 8 }}
      {{- end }}
    - match: Host(`{{ $url }}`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: {{ printf "%s-api" $fullName | quote }}
          port: {{ $.Values.api.servicePort }}
      {{- with $entry.middlewares }}
      middlewares: {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $.Values.providers }}
    {{- range $providerName, $provider := . }}
    {{- if $provider.enabled }}
    {{/* $providerName & $providerUrlBase ordering matters here, as we want
         $provider.nameOverride to affect the $providerUrlBase.
    */}}
    {{- $providerName := $provider.name | default $providerName }}
    {{- $providerUrlBase := $provider.urlBaseOverride | default (printf "/import/%s" $providerName) }}
    - match: Host(`{{ $url }}`) && PathPrefix(`{{ $providerUrlBase }}`)
      kind: Rule
      services:
        - name: {{ printf "%s-%s" $fullName $providerName | quote }}
          port: {{ $provider.servicePort | default 80 }}
      {{- with $entry.middlewares }}
      middlewares: {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}{{/* if provider.enabled */}}
    {{- end }}{{/* range of providers */}}
    {{- end }}{{/* with .Values.providers */}}
    {{- with $.Values.ingressRoute.extraRoutes }}
      {{- . | toYaml | nindent 4 }}
    {{- end }}{{/* with .Values.ingressRoute.extraRoutes */}}
  {{- with $entry.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}{{/* range .Values.ingressRoute.entries */}}
{{- end }}{{/* if .Values.ingressRoute.enabled */}}
