{{- if .Values.ingress.enabled -}}
{{- $fullName := include "wharf-helm.fullname" . -}}
{{- $svcPortWeb := .Values.web.servicePort -}}
{{- $svcPortApi := .Values.api.servicePort -}}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
{{- else if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName | quote }}
  labels: {{- include "wharf-helm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.global.url | quote }}
      secretName: {{ .Values.ingress.tls.secretName }}
{{- end }}
  rules:
    - host: {{ .Values.global.url | quote }}
      http:
        paths:
          - path: /
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%v-web" $fullName | quote }}
                port:
                  number: {{ $svcPortWeb }}
{{- else }}
            backend:
              serviceName: {{ printf "%v-web" $fullName | quote }}
              servicePort: {{ $svcPortWeb }}
{{- end }}
          - path: /api
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%v-api" $fullName | quote }}
                port:
                  number: {{ $svcPortApi }}
{{- else }}
            backend:
              serviceName: {{ printf "%v-api" $fullName | quote }}
              servicePort: {{ $svcPortApi }}
{{- end }}
          {{- with .Values.providers }}
          {{- range $providerName, $provider := . }}
          {{- if $provider.enabled }}
          {{/* $providerName & $providerUrlBase ordering matters here, as we want
               $provider.nameOverride to affect the $providerUrlBase.
          */}}
          {{- $providerName := $provider.name | default $providerName }}
          {{- $providerUrlBase := $provider.urlBaseOverride | default (printf "/import/%s" $providerName) }}
          - path: {{ $providerUrlBase | quote }}
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" $fullName $providerName | quote }}
                port:
                  number: {{ $provider.servicePort | default 80 }}
{{- else }}
            backend:
              serviceName: {{ printf "%s-%s" $fullName $providerName | quote }}
              servicePort: {{ $provider.servicePort | default 80 }}
{{- end }}
          {{- end }}{{/* if provider.enabled */}}
          {{- end }}{{/* range of providers */}}
          {{- end }}{{/* with .Values.providers */}}
          {{- with .Values.ingress.extraPaths }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}{{/* with .Values.ingress.extraPaths */}}
{{- end }}
