apiVersion: v2
name: wharf-helm
description: Deploy Wharf to Kubernetes
type: application
version: 3.2.4
home: https://github.com/iver-wharf/wharf-helm/blob/master/charts/wharf-helm
maintainers:
  - name: jilleJr
    email: kalle.fagerberg@iver.se
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: support
      url: https://github.com/iver-wharf/wharf-helm/issues/new
