web:
  imagePullPolicy: IfNotPresent ## NON-DEFAULT
  
  podSecurityContext:
    fsGroup: 2000
  
  containerSecurityContext:
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

api:
  imagePullPolicy: IfNotPresent

  podSecurityContext:
    fsGroup: 2000

  containerSecurityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  db:
    host: wharf-db.default.svc.cluster.local

  extraEnvs:
    - name: FOO_BAR
      value: foo-bar

ingress:
  enabled: true
