web:
  imagePullPolicy: IfNotPresent ## NON-DEFAULT
  
  podSecurityContext:
    fsGroup: 2000
  
  containerSecurityContext:
    capabilities:
      drop:
      - ALL
      add:
      - NET_BIND_SERVICE
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  http:
    oidc:
      authority: "https://login.microsoftonline.com/841df554-ef9d-48b1-bc6e-44cf8543a8fc/v2.0/.well-known/openid-configuration"
      clientId: "01fcb3dc-7a2b-4b1c-a7d6-d7033089c779"
      scope: "openid profile email offline_access api://wharf-internal/read api://wharf-internal/admin api://wharf-internal/deploy"
      logLevel: "debug"
      useRefreshToken: true
      silentRenew: true
      ignoreNonceAfterRefresh: true
      maxIdTokenIatOffsetAllowedInSeconds: 600

api:
  imagePullPolicy: IfNotPresent

  podSecurityContext:
    fsGroup: 2000

  containerSecurityContext:
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  db:
    host: wharf-db.default.svc.cluster.local

  extraEnvs:
    - name: FOO_BAR
      value: foo-bar

ingress:
  enabled: true
