name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      # Required by helm/chart-testing-action
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      # Required by helm/chart-testing-action
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint --lint-conf .github/ct.yaml

  lint-docs:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Run helm-docs
        run: .github/helm-docs.sh

  kubeval-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    strategy:
      matrix:
        k8s:
          - v1.12.10
          - v1.13.11
          - v1.14.10
          - v1.15.7
          - v1.16.4
          - v1.17.4
          - v1.18.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Run kubeval
        run: .github/kubeval.sh ${{ matrix.k8s }}
