{{- if .Values.aggregator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wharf-cmd.fullname" . }}-aggregator
  labels:
    component: aggregator
    {{- include "wharf-cmd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: aggregator
      {{- include "wharf-cmd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: aggregator
        {{- include "wharf-cmd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wharf-cmd
      {{- with .Values.aggregator.imagePullSecrets | default .Values.common.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: aggregator
          image: {{ .Values.aggregator.image | default .Values.common.image | quote }}
          {{- with .Values.aggregator.imagePullPolicy | default .Values.common.imagePullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          args: 
            - --loglevel
            - {{ .Values.aggregator.loglevel | default .Values.common.loglevel | quote }}
            - aggregator
            - serve
            {{- with .Values.aggregator.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.aggregator.extraEnvs }}
          env: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - mountPath: /etc/iver-wharf/wharf-cmd
            name: config
            readOnly: true
      {{- with .Values.aggregator.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregator.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.aggregator.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "wharf-cmd.fullname" . }}-aggregator-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wharf-cmd.fullname" . }}-aggregator-config
  labels:
    component: aggregator
    {{- include "wharf-cmd.labels" . | nindent 4 }}
data:
  {{- $config := deepCopy .Values.common.config | merge .Values.aggregator.config }}
  {{- $config = dict "instanceId" .Values.global.instanceId | merge $config }}
  wharf-cmd-config.yml: |
    {{- $config | toYaml | nindent 4 }}
{{- end }}
