{{- if .Values.watchdog.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wharf-cmd.fullname" . }}-watchdog
  labels:
    component: watchdog
    {{- include "wharf-cmd.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: watchdog
      {{- include "wharf-cmd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: watchdog
        {{- include "wharf-cmd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: wharf-cmd
      {{- with .Values.watchdog.imagePullSecrets | default .Values.common.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: watchdog
          image: {{ .Values.watchdog.image | default .Values.common.image | quote }}
          {{- with .Values.watchdog.imagePullPolicy | default .Values.common.imagePullPolicy }}
          imagePullPolicy: {{ . | quote }}
          {{- end }}
          args: 
            - --loglevel
            - {{ .Values.watchdog.loglevel | default .Values.common.loglevel | quote }}
            - watchdog
            - serve
            {{- with .Values.watchdog.extraArgs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.watchdog.extraEnvs }}
          env: {{- toYaml . | nindent 12}}
          {{- end }}
          volumeMounts:
          - mountPath: /etc/iver-wharf/wharf-cmd
            name: config
            readOnly: true
      {{- with .Values.watchdog.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.watchdog.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "wharf-cmd.fullname" . }}-watchdog-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wharf-cmd.fullname" . }}-watchdog-config
  labels:
    component: watchdog
    {{- include "wharf-cmd.labels" . | nindent 4 }}
data:
  wharf-cmd-config.yml: |
    instanceId: {{ .Values.global.instanceId | quote }}
    {{- deepCopy .Values.common.config | merge .Values.watchdog.config | toYaml | nindent 4 }}
{{- end }}
