---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wharf-cmd.fullname" . }}-worker-config
  labels:
    component: worker
    {{- include "wharf-cmd.labels" . | nindent 4 }}
data:
  {{- $config := deepCopy .Values.common.config | merge .Values.worker.config }}
  {{- $config = dict "instanceId" .Values.global.instanceId | merge $config }}
  wharf-cmd-config.yml: |
    {{- $config | toYaml | nindent 4 }}

  {{- $wharfVars := .Values.worker.vars | default dict }}
  wharf-vars.yml: |
    vars: {{- $wharfVars | toYaml | nindent 6 }}
